export const categories = [
  { name: 'All books', count: '248' },
  { name: 'Fiction', count: '86' },
  { name: 'Nonfiction', count: '64' },
  { name: 'Mystery', count: '32' },
  { name: 'Fantasy', count: '28' },
  { name: 'Poetry', count: '18' },
]

export const books = [
  {
    id: 'creative-act',
    title: 'The Creative Act',
    author: 'Rick Rubin',
    category: 'Nonfiction',
    price: 24.5,
    rating: 4.9,
    badge: 'Bestseller',
    isbn: '9780593652886',
    color: 'mint',
  },
  {
    id: 'midnight-library',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    category: 'Fiction',
    price: 18.0,
    rating: 4.8,
    badge: 'Staff pick',
    isbn: '9780525559474',
    color: 'blue',
  },
  {
    id: 'yellowface',
    title: 'Yellowface',
    author: 'R. F. Kuang',
    category: 'Fiction',
    price: 21.0,
    rating: 4.7,
    badge: 'Trending',
    isbn: '9780063250833',
    color: 'yellow',
  },
  {
    id: 'psychology-of-money',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    category: 'Nonfiction',
    price: 19.5,
    rating: 4.8,
    badge: 'Reader favorite',
    isbn: '9780857197689',
    color: 'coral',
  },
  {
    id: 'dune',
    title: 'Dune',
    author: 'Frank Herbert',
    category: 'Fantasy',
    price: 17.0,
    rating: 4.9,
    badge: 'Classic',
    isbn: '9780441013593',
    color: 'sand',
  },
  {
    id: 'educated',
    title: 'Educated',
    author: 'Tara Westover',
    category: 'Nonfiction',
    price: 20.0,
    rating: 4.7,
    badge: 'Book club',
    isbn: '9780399590504',
    color: 'plum',
  },
  {
    id: 'sapiens',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    category: 'Nonfiction',
    price: 22.0,
    rating: 4.8,
    badge: 'Bestseller',
    isbn: '9780062316097',
    color: 'sky',
  },
  {
    id: 'house-of-cerulean-sea',
    title: 'The House in the Cerulean Sea',
    author: 'TJ Klune',
    category: 'Fantasy',
    price: 19.0,
    rating: 4.9,
    badge: 'Feel-good read',
    isbn: '9781250217288',
    color: 'peach',
  },
]
